### ISSUE TITLE
wrong amount captured in razorpay payment

### ISSUE THREAD

**Issue by ramnathkrish** [razorpay/razorpay-whmcs#82]
Hi Team,
below example

Ex : invoice amount is ₹22894.96 
after payment from razorpay. invoice is updated with actual invoiced ₹22894.96  amount. but paid amount ₹ 17,611.50 in razorpay which is confusing the customer and we got loss of ₹ 5,283.46

**Comment by ramnathkrish** [comment]
i also raised this issue to concerned team. please reach out to merchant formore details. 

 reference ticket ID:  12022991

**Comment by ramnathkrish** [comment]
Below are steps to reproduce the issue. 

Example :
Create a New invoice in whmcs for any customer with any product  with Rs. 500.
Try to pay using razorpay it will show you to pay Rs. 500 ( Don't want to do payment )

Goto same invoice and modify the price Rs. 500 to Rs. 300 
try to pay using razorpay it will show you to pay Rs. 500   ( Don't want to do payment ) showing wrong amount
Expected amount to show Rs. 300

Goto same invoice and modify the price Rs. 500 to Rs. 1000
try to pay using razorpay it will show you to pay Rs. 500   ( Don't want to do payment ) showing wrong amount
Expected amount to show Rs. 1000

**Comment by MeraHost** [comment]
Facing same issue, is it solved?

**Comment by youstable** [comment]
Raised a request with them, but their development team doesn't care we are losing money and requires manual work to do every time we need to update the invoices

**Comment by rohitcbr** [comment]
@youstable @MeraHost can you please upgrade razorpay-whmcs module to 2.2.2 (https://github.com/razorpay/razorpay-whmcs/releases/tag/2.2.2). Here we have fixed the bug

**Comment by MeraHost** [comment]
> @youstable @MeraHost can you please upgrade razorpay-whmcs module to 2.2.2 (https://github.com/razorpay/razorpay-whmcs/releases/tag/2.2.2). Here we have fixed the bug

Let me check and update

**Comment by rohitcbr** [comment]
@MeraHost is the issue fixed at your side?

**Comment by MakarandMane** [comment]
> **WHMCS v8.10.1 PHP Version 8.1.29**
> 
> This issue happening after updated to latest razorpay module [2.2.1](https://github.com/razorpay/razorpay-whmcs/releases/tag/2.2.1) its working fine in the version [2.2.0](https://github.com/razorpay/razorpay-whmcs/releases/tag/2.2.0)
> 
> **Below are steps to reproduce the issue.**
> 
> **Example :** Create a New invoice in whmcs for any customer with any product with Rs. 500. Try to pay using razorpay it will show you to pay Rs. 500 ( Don't want to do payment )
> 
> Goto same invoice and modify the Amount Rs. 500 to Rs. 300 try to pay using razorpay it will show you to pay Rs. 500 ( Don't want to do payment ) showing wrong amount Expected amount to show Rs. 300
> 
> Goto same invoice and modify the Amount Rs. 500 to Rs. 1000 try to pay using razorpay it will show you to pay Rs. 500 ( Don't want to do payment ) showing wrong amount Expected amount to show Rs. 1000

I am also faced this issue today.
I was having original invoice of 22500 & I modified it to 23900. Customer can see new amount but paid only 22500, as razorpay module couldn't capture new amount. 
then i modified transaction amount & set invoice again to unpaid. In this case razorpay comes with error & could not capture remaining amount.

**Comment by rohitcbr** [comment]
@MakarandMane please upgrade razorpay-whmcs to the latest version 2.2.2 and check

**Comment by MakarandMane** [comment]
> @MakarandMane please upgrade razorpay-whmcs to the latest version 2.2.2 and check

I updated & it is working now. Why this issue still kept open? You should mark this as resolved with your commit.

**Comment by rohitcbr** [comment]
Issue resolved with the release razorpay-whmcs:2.2.2
